using System;
using System.Collections.Generic;
using System.Text;

namespace AdSystem.RTBSystem
{
    class RTBConfiguration
    {
        public int timeout;
        public string version;
        public Dictionary<string, string> categories;

        public RTBConfiguration(int _timeout, string _version)
        {
            this.timeout = _timeout;
            this.version = _version;

            this.categories = new Dictionary<string, string>();
            categories.Add("IAB1-1", "Books & Literature");
            categories.Add("IAB1-2", "Celebrity Fan/Gossip");
            categories.Add("IAB1-3", "Fine Art");
            categories.Add("IAB1-4", "Humor");
            categories.Add("IAB1-5", "Movies");
            categories.Add("IAB1-6", "Music");
            categories.Add("IAB1-7", "Television");
            categories.Add("IAB2", "Automotive");
            categories.Add("IAB2-1", "Auto Parts");
            categories.Add("IAB2-2", "Auto Repair");
            categories.Add("IAB2-3", "Buying/Selling Cars");
            categories.Add("IAB2-4", "Car Culture");
            categories.Add("IAB2-5", "Certified Pre-Owned");
            categories.Add("IAB2-6", "Convertible");
            categories.Add("IAB2-7", "Coupe");
            categories.Add("IAB2-8", "Crossover");
            categories.Add("IAB2-9", "Diesel");
            categories.Add("IAB2-10", "Electric Vehicle");
            categories.Add("IAB2-11", "Hatchback");
            categories.Add("IAB2-12", "Hybrid");
            categories.Add("IAB2-13", "Luxury");
            categories.Add("IAB2-14", "Minivan");
            categories.Add("IAB2-15", "Motorcycles");
            categories.Add("IAB2-16", "Off-Road Vehicles");
            categories.Add("IAB2-17", "Performance Vehicles");
            categories.Add("IAB2-18", "Pickup");
            categories.Add("IAB2-19", "Road-Side Assistance");
            categories.Add("IAB2-20", "Sedan");
            categories.Add("IAB2-21", "Trucks & Accessories");
            categories.Add("IAB2-22", "Vintage Cars");
            categories.Add("IAB2-23", "Wagon");
            categories.Add("IAB3", "Business");
            categories.Add("IAB3-1", "Advertising");
            categories.Add("IAB3-2", "Agriculture");
            categories.Add("IAB3-3", "Biotech/Biomedical");
            categories.Add("IAB3-4", "Business Software");
            categories.Add("IAB3-5", "Construction");
            categories.Add("IAB3-6", "Forestry");
            categories.Add("IAB3-7", "Government");
            categories.Add("IAB3-8", "Green Solutions");
            categories.Add("IAB3-9", "Human Resources");
            categories.Add("IAB3-10", "Logistics");
            categories.Add("IAB3-11", "Marketing");
            categories.Add("IAB3-12", "Metals");
            categories.Add("IAB4", "Careers");
            categories.Add("IAB4-1", "Career Planning");
            categories.Add("IAB4-2", "College");
            categories.Add("IAB4-3", "Financial Aid");
            categories.Add("IAB4-4", "Job Fairs");
            categories.Add("IAB4-5", "Job Search");
            categories.Add("IAB4-6", "Resume Writing/Advice");
            categories.Add("IAB4-7", "Nursing");
            categories.Add("IAB4-8", "Scholarships");
            categories.Add("IAB4-9", "Telecommuting");
            categories.Add("IAB4-10", "U.S. Military");
            categories.Add("IAB4-11", "Career Advice");
            categories.Add("IAB5", "Education");
            categories.Add("IAB5-1", "7-12 Education");
            categories.Add("IAB5-2", "Adult Education");
            categories.Add("IAB5-3", "Art History");
            categories.Add("IAB5-4", "College Administration");
            categories.Add("IAB5-5", "College Life");
            categories.Add("IAB5-6", "Distance Learning");
            categories.Add("IAB5-7", "English as a 2nd Language");
            categories.Add("IAB5-8", "Language Learning");
            categories.Add("IAB5-9", "Graduate School");
            categories.Add("IAB5-10", "Homeschooling");
            categories.Add("IAB5-11", "Homework/Study Tips");
            categories.Add("IAB5-12", "K-6 Educators");
            categories.Add("IAB5-13", "Private School");
            categories.Add("IAB5-14", "Special Education");
            categories.Add("IAB5-15", "Studying Business");
            categories.Add("IAB6", "Family & Parenting");
            categories.Add("IAB6-1", "Adoption");
            categories.Add("IAB6-2", "Babies & Toddlers");
            categories.Add("IAB6-3", "Daycare/Pre School");
            categories.Add("IAB6-4", "Family Internet");
            categories.Add("IAB6-5", "Parenting - K-6 Kids");
            categories.Add("IAB6-6", "Parenting teens");
            categories.Add("IAB6-7", "Pregnancy");
            categories.Add("IAB6-8", "Special Needs Kids");
            categories.Add("IAB6-9", "Eldercare");
            categories.Add("IAB7", "Health & Fitness");
            categories.Add("IAB7-1", "Exercise");
            categories.Add("IAB7-2", "ADD");
            categories.Add("IAB7-3", "AIDS/HIV");
            categories.Add("IAB7-4", "Allergies");
            categories.Add("IAB7-5", "Alternative Medicine");
            categories.Add("IAB7-6", "Arthritis");
            categories.Add("IAB7-7", "Asthma");
            categories.Add("IAB7-8", "Autism/PDD");
            categories.Add("IAB7-9", "Bipolar Disorder");
            categories.Add("IAB7-10", "Brain Tumor");
            categories.Add("IAB7-11", "Cancer");
            categories.Add("IAB7-12", "Cholesterol");
            categories.Add("IAB7-13", "Chronic Fatigue Syndrome");
            categories.Add("IAB7-14", "Chronic Pain");
            categories.Add("IAB7-15", "Cold & Flu");
            categories.Add("IAB7-16", "Deafness");
            categories.Add("IAB7-17", "Dental Care");
            categories.Add("IAB7-18", "Depression");
            categories.Add("IAB7-19", "Dermatology");
            categories.Add("IAB7-20", "Diabetes");
            categories.Add("IAB7-21", "Epilepsy");
            categories.Add("IAB7-22", "GERD/Acid Reflux");
            categories.Add("IAB7-23", "Headaches/Migraines");
            categories.Add("IAB7-24", "Heart Disease");
            categories.Add("IAB7-25", "Herbs for Health");
            categories.Add("IAB7-26", "Holistic Healing");
            categories.Add("IAB7-27", "IBS/CrohnÔÇÖs Disease");
            categories.Add("IAB7-28", "Incest/Abuse Support");
            categories.Add("IAB7-29", "Incontinence");
            categories.Add("IAB7-30", "Infertility");
            categories.Add("IAB7-31", "MenÔÇÖs Health");
            categories.Add("IAB7-32", "Nutrition");
            categories.Add("IAB7-33", "Orthopedics");
            categories.Add("IAB7-34", "Panic/Anxiety Disorders");
            categories.Add("IAB7-35", "Pediatrics");
            categories.Add("IAB7-36", "Physical Therapy");
            categories.Add("IAB7-37", "Psychology/Psychiatry");
            categories.Add("IAB7-38", "Senior Health");
            categories.Add("IAB7-39", "Sexuality");
            categories.Add("IAB7-40", "Sleep Disorders");
            categories.Add("IAB7-41", "Smoking Cessation");
            categories.Add("IAB7-42", "Substance Abuse");
            categories.Add("IAB7-43", "Thyroid Disease");
            categories.Add("IAB7-44", "Weight Loss");
            categories.Add("IAB7-45", "Women's Health");
            categories.Add("IAB8", "Food & Drink");
            categories.Add("IAB8-1", "American Cuisine");
            categories.Add("IAB8-2", "Barbecues & Grilling");
            categories.Add("IAB8-3", "Cajun/Creole");
            categories.Add("IAB8-4", "Chinese Cuisine");
            categories.Add("IAB8-5", "Cocktails/Beer");
            categories.Add("IAB8-6", "Coffee/Tea");
            categories.Add("IAB8-7", "Cuisine-Specific");
            categories.Add("IAB8-8", "Desserts & Baking");
            categories.Add("IAB8-9", "Dining Out");
            categories.Add("IAB8-10", "Food Allergies");
            categories.Add("IAB8-11", "French Cuisine");
            categories.Add("IAB8-12", "Health/Low-Fat Cooking");
            categories.Add("IAB8-13", "Italian Cuisine");
            categories.Add("IAB8-14", "Japanese Cuisine");
            categories.Add("IAB8-15", "Mexican Cuisine");
            categories.Add("IAB8-16", "Vegan");
            categories.Add("IAB8-17", "Vegetarian");
            categories.Add("IAB8-18", "Wine");
            categories.Add("IAB9", "Hobbies & Interests");
            categories.Add("IAB9-1", "Art/Technology");
            categories.Add("IAB9-2", "Arts & Crafts");
            categories.Add("IAB9-3", "Beadwork");
            categories.Add("IAB9-4", "Bird-Watching");
            categories.Add("IAB9-5", "Board Games/Puzzles");
            categories.Add("IAB9-6", "Candle & Soap Making");
            categories.Add("IAB9-7", "Card Games");
            categories.Add("IAB9-8", "Chess");
            categories.Add("IAB9-9", "Cigars");
            categories.Add("IAB9-10", "Collecting");
            categories.Add("IAB9-11", "Comic Books");
            categories.Add("IAB9-12", "Drawing/Sketching");
            categories.Add("IAB9-13", "Freelance Writing");
            categories.Add("IAB9-14", "Genealogy");
            categories.Add("IAB9-15", "Getting Published");
            categories.Add("IAB9-16", "Guitar");
            categories.Add("IAB9-17", "Home Recording");
            categories.Add("IAB9-18", "Investors & Patents");
            categories.Add("IAB9-19", "Jewelry Making");
            categories.Add("IAB9-20", "Magic & Illusion");
            categories.Add("IAB9-21", "Needlework");
            categories.Add("IAB9-22", "Painting");
            categories.Add("IAB9-23", "Photography");
            categories.Add("IAB9-24", "Radio");
            categories.Add("IAB9-25", "Roleplaying Games");
            categories.Add("IAB9-26", "Sci-Fi & Fantasy");
            categories.Add("IAB9-27", "Scrapbooking");
            categories.Add("IAB9-28", "Screenwriting");
            categories.Add("IAB9-29", "Stamps & Coins");
            categories.Add("IAB9-30", "Video & Computer Games");
            categories.Add("IAB9-31", "Woodworking");
            categories.Add("IAB10", "Home & Garden");
            categories.Add("IAB10-1", "Appliances");
            categories.Add("IAB10-2", "Entertaining");
            categories.Add("IAB10-3", "Environmental Safety");
            categories.Add("IAB10-4", "Gardening");
            categories.Add("IAB10-5", "Home Repair");
            categories.Add("IAB10-6", "Home Theater");
            categories.Add("IAB10-7", "Interior Decorating");
            categories.Add("IAB10-8", "Landscaping");
            categories.Add("IAB10-9", "Remodeling & Construction");
            categories.Add("IAB11", "Law, Government, & Politics");
            categories.Add("IAB11-1", "Immigration");
            categories.Add("IAB11-2", "Legal Issues");
            categories.Add("IAB11-3", "U.S. Government Resources");
            categories.Add("IAB11-4", "Politics");
            categories.Add("IAB11-5", "Commentary");
            categories.Add("IAB12", "News");
            categories.Add("IAB12-1", "International News");
            categories.Add("IAB12-2", "National News");
            categories.Add("IAB12-3", "Local News");
            categories.Add("IAB13", "Personal Finance");
            categories.Add("IAB13-1", "Beginning Investing");
            categories.Add("IAB13-2", "Credit/Debt & Loans");
            categories.Add("IAB13-3", "Financial News");
            categories.Add("IAB13-4", "Financial Planning");
            categories.Add("IAB13-5", "Hedge Fund");
            categories.Add("IAB13-6", "Insurance");
            categories.Add("IAB13-7", "Investing");
            categories.Add("IAB13-8", "Mutual Funds");
            categories.Add("IAB13-9", "Options");
            categories.Add("IAB13-10", "Retirement Planning");
            categories.Add("IAB13-11", "Stocks");
            categories.Add("IAB13-12", "Tax Planning");
            categories.Add("IAB14", "Society");
            categories.Add("IAB14-1", "Dating");
            categories.Add("IAB14-2", "Divorce Support");
            categories.Add("IAB14-3", "Gay Life");
            categories.Add("IAB14-4", "Marriage");
            categories.Add("IAB14-5", "Senior Living");
            categories.Add("IAB14-6", "Teens");
            categories.Add("IAB14-7", "Weddings");
            categories.Add("IAB14-8", "Ethnic Specific");
            categories.Add("IAB15", "Science");
            categories.Add("IAB15-1", "Astrology");
            categories.Add("IAB15-2", "Biology");
            categories.Add("IAB15-3", "Chemistry");
            categories.Add("IAB15-4", "Geology");
            categories.Add("IAB15-5", "Paranormal Phenomena");
            categories.Add("IAB15-6", "Physics");
            categories.Add("IAB15-7", "Space/Astronomy");
            categories.Add("IAB15-8", "Geography");
            categories.Add("IAB15-9", "Botany");
            categories.Add("IAB15-10", "Weather");
            categories.Add("IAB16", "Pets");
            categories.Add("IAB16-1", "Aquariums");
            categories.Add("IAB16-2", "Birds");
            categories.Add("IAB16-3", "Cats");
            categories.Add("IAB16-4", "Dogs");
            categories.Add("IAB16-5", "Large Animals");
            categories.Add("IAB16-6", "Reptiles");
            categories.Add("IAB16-7", "Veterinary Medicine");
            categories.Add("IAB17", "Sports");
            categories.Add("IAB17-1", "Auto Racing");
            categories.Add("IAB17-2", "Baseball");
            categories.Add("IAB17-3", "Bicycling");
            categories.Add("IAB17-4", "Bodybuilding");
            categories.Add("IAB17-5", "Boxing");
            categories.Add("IAB17-6", "Canoeing/Kayaking");
            categories.Add("IAB17-7", "Cheerleading");
            categories.Add("IAB17-8", "Climbing");
            categories.Add("IAB17-9", "Cricket");
            categories.Add("IAB17-10", "Figure Skating");
            categories.Add("IAB17-11", "Fly Fishing");
            categories.Add("IAB17-12", "Football");
            categories.Add("IAB17-13", "Freshwater Fishing");
            categories.Add("IAB17-14", "Game & Fish");
            categories.Add("IAB17-15", "Golf");
            categories.Add("IAB17-16", "Horse Racing");
            categories.Add("IAB17-17", "Horses");
            categories.Add("IAB17-18", "Hunting/Shooting");
            categories.Add("IAB17-19", "Inline Skating");
            categories.Add("IAB17-20", "Martial Arts");
            categories.Add("IAB17-21", "Mountain Biking");
            categories.Add("IAB17-22", "NASCAR Racing");
            categories.Add("IAB17-23", "Olympics");
            categories.Add("IAB17-24", "Paintball");
            categories.Add("IAB17-25", "Power & Motorcycles");
            categories.Add("IAB17-26", "Pro Basketball");
            categories.Add("IAB17-27", "Pro Ice Hockey");
            categories.Add("IAB17-28", "Rodeo");
            categories.Add("IAB17-29", "Rugby");
            categories.Add("IAB17-30", "Running/Jogging");
            categories.Add("IAB17-31", "Sailing");
            categories.Add("IAB17-32", "Saltwater Fishing");
            categories.Add("IAB17-33", "Scuba Diving");
            categories.Add("IAB17-34", "Skateboarding");
            categories.Add("IAB17-35", "Skiing");
            categories.Add("IAB17-36", "Snowboarding");
            categories.Add("IAB17-37", "Surfing/Body-Boarding");
            categories.Add("IAB17-38", "Swimming");
            categories.Add("IAB17-39", "Table Tennis/Ping-Pong");
            categories.Add("IAB17-40", "Tennis");
            categories.Add("IAB17-41", "Volleyball");
            categories.Add("IAB17-42", "Walking");
            categories.Add("IAB17-43", "Waterski/Wakeboard");
            categories.Add("IAB17-44", "World Soccer");
            categories.Add("IAB18", "Style & Fashion");
            categories.Add("IAB18-1", "Beauty");
            categories.Add("IAB18-2", "Body Art");
            categories.Add("IAB18-3", "Fashion");
            categories.Add("IAB18-4", "Jewelry");
            categories.Add("IAB18-5", "Clothing");
            categories.Add("IAB18-6", "Accessories");
            categories.Add("IAB19", "Technology & Computing");
            categories.Add("IAB19-1", "3-D Graphics");
            categories.Add("IAB19-2", "Animation");
            categories.Add("IAB19-3", "Antivirus Software");
            categories.Add("IAB19-4", "C/C++");
            categories.Add("IAB19-5", "Cameras & Camcorders");
            categories.Add("IAB19-6", "Cell Phones");
            categories.Add("IAB19-7", "Computer Certification");
            categories.Add("IAB19-8", "Computer Networking");
            categories.Add("IAB19-9", "Computer Peripherals");
            categories.Add("IAB19-10", "Computer Reviews");
            categories.Add("IAB19-11", "Data Centers");
            categories.Add("IAB19-12", "Databases");
            categories.Add("IAB19-13", "Desktop Publishing");
            categories.Add("IAB19-14", "Desktop Video");
            categories.Add("IAB19-15", "Email");
            categories.Add("IAB19-16", "Graphics Software");
            categories.Add("IAB19-17", "Home Video/DVD");
            categories.Add("IAB19-18", "Internet Technology");
            categories.Add("IAB19-19", "Java");
            categories.Add("IAB19-20", "JavaScript");
            categories.Add("IAB19-21", "Mac Support");
            categories.Add("IAB19-22", "MP3/MIDI");
            categories.Add("IAB19-23", "Net Conferencing");
            categories.Add("IAB19-24", "Net for Beginners");
            categories.Add("IAB19-25", "Network Security");
            categories.Add("IAB19-26", "Palmtops/PDAs");
            categories.Add("IAB19-27", "PC Support");
            categories.Add("IAB19-28", "Portable");
            categories.Add("IAB19-29", "Entertainment");
            categories.Add("IAB19-30", "Shareware/Freeware");
            categories.Add("IAB19-31", "Unix");
            categories.Add("IAB19-32", "Visual Basic");
            categories.Add("IAB19-33", "Web Clip Art");
            categories.Add("IAB19-34", "Web Design/HTML");
            categories.Add("IAB19-35", "Web Search");
            categories.Add("IAB19-36", "Windows");
            categories.Add("IAB20", "Travel");
            categories.Add("IAB20-1", "Adventure Travel");
            categories.Add("IAB20-2", "Africa");
            categories.Add("IAB20-3", "Air Travel");
            categories.Add("IAB20-4", "Australia & New Zealand");
            categories.Add("IAB20-5", "Bed & Breakfasts");
            categories.Add("IAB20-6", "Budget Travel");
            categories.Add("IAB20-7", "Business Travel");
            categories.Add("IAB20-8", "By US Locale");
            categories.Add("IAB20-9", "Camping");
            categories.Add("IAB20-10", "Canada");
            categories.Add("IAB20-11", "Caribbean");
            categories.Add("IAB20-12", "Cruises");
            categories.Add("IAB20-13", "Eastern Europe");
            categories.Add("IAB20-14", "Europe");
            categories.Add("IAB20-15", "France");
            categories.Add("IAB20-16", "Greece");
            categories.Add("IAB20-17", "Honeymoons/Getaways");
            categories.Add("IAB20-18", "Hotels");
            categories.Add("IAB20-19", "Italy");
            categories.Add("IAB20-20", "Japan");
            categories.Add("IAB20-21", "Mexico & Central America");
            categories.Add("IAB20-22", "National Parks");
            categories.Add("IAB20-23", "South America");
            categories.Add("IAB20-24", "Spas");
            categories.Add("IAB20-25", "Theme Parks");
            categories.Add("IAB20-26", "Traveling with Kids");
            categories.Add("IAB20-27", "United Kingdom");
            categories.Add("IAB21", "Real Estate");
            categories.Add("IAB21-1", "Apartments");
            categories.Add("IAB21-2", "Architects");
            categories.Add("IAB21-3", "Buying/Selling Homes");
            categories.Add("IAB22", "Shopping");
            categories.Add("IAB22-1", "Contests & Freebies");
            categories.Add("IAB22-2", "Couponing");
            categories.Add("IAB22-3", "Comparison");
            categories.Add("IAB22-4", "Engines");
            categories.Add("IAB23", "Religion & Spirituality");
            categories.Add("IAB23-1", "Alternative Religions");
            categories.Add("IAB23-2", "Atheism/Agnosticism");
            categories.Add("IAB23-3", "Buddhism");
            categories.Add("IAB23-4", "Catholicism");
            categories.Add("IAB23-5", "Christianity");
            categories.Add("IAB23-6", "Hinduism");
            categories.Add("IAB23-7", "Islam");
            categories.Add("IAB23-8", "Judaism");
            categories.Add("IAB23-9", "Latter-Day Saints");
            categories.Add("IAB23-10", "Pagan/Wiccan");
            categories.Add("IAB24", "Uncategorized");
            categories.Add("IAB25", "Non-Standard Content");
            categories.Add("IAB25-1", "Unmoderated UGC");
            categories.Add("IAB25-2", "Extreme Graphic/Explicit Violence");
            categories.Add("IAB25-3", "Pornography");
            categories.Add("IAB25-4", "Profane Content");
            categories.Add("IAB25-5", "Hate Content");
            categories.Add("IAB25-6", "Under Construction");
            categories.Add("IAB25-7", "Incentivized");
            categories.Add("IAB26", "Illegal Content");
            categories.Add("IAB26-1", "Illegal Content");
            categories.Add("IAB26-2", "Warez");
            categories.Add("IAB26-3", "Spyware/Malware");
            categories.Add("IAB26-4", "Copyright Infringement");
        }
    }
}
